export { default as arrowDownIcon } from "./arrow_down.svg";
export { default as chevronBackward } from "./chevron_backward.svg";
export { default as chevronForward } from "./chevron_forward.svg";
export { default as reportIcon } from "./report.svg";
export { default as checkCircle } from "./check_circle.svg";
export { default as checkedCircle } from "./checked_circle.svg";
export { default as eye } from "./eye.svg";
export { default as like } from "./likes.svg";
export { default as commentIcon } from "./comments.svg";
export { default as insta } from "./insta.svg";
export { default as X } from "./x.svg";
export { default as scrap } from "./scrap.svg";
export { default as menu } from "./menu.svg";
export { default as profile } from "./profile.svg";
export { default as favorite } from "./favorite.svg";
export { default as bookmark } from "./bookmark.svg";
export { default as search } from "./search.svg";
export { default as backward } from "./backward.svg";
export { default as forward } from "./forward.svg";
export { default as more } from "./more.svg";
export { default as whitescrap } from "./whitescrap.svg";
export { default as bestBadge } from "./best.svg";
export { default as writeIcon } from "./pencil.svg";
export { default as left } from "./left.svg";
export { default as right } from "./right.svg";
export { default as addPhotoIcon } from "./add_photo.svg";
export { default as cancelIcon } from "./cancel.svg";
export { default as logo } from "./logo.svg";
export { default as bArrowDown } from "./b_arrow_down.svg";
export { default as darkHeart } from "./darkHeart.svg";
export { default as darkBookmark } from "./darkBookmark.svg";
export {default as afterscrap} from "./afterscrap.svg";
export {default as blackscrap} from "./blackscrap.svg";
export {default as whitefilledscrap} from "./whitefilledscrap.svg";
export {default as banner} from "./banner.svg";
export {default as likesIcon} from "./emptyHeart.svg";
export {default as likes} from "./heart.svg";
export {default as logo2} from "./logo2.svg"
export {default as whiteHeart} from "./whiteHeart.svg"